@startuml
actor CallCenterEmployee
actor Patient

rectangle MisterEdSystem {

    usecase ViewQueue
    usecase CallPatient
    usecase ViewPatientInfo
    usecase NotifyED

}


CallCenterEmployee -> ViewQueue : "Check current queue"
CallCenterEmployee -> ViewPatientInfo: "View patient information"
CallCenterEmployee -> CallPatient : "Proceed with next call"
CallCenterEmployee -> NotifyED : "Notify ED staff"



ViewPatientInfo --> ViewQueue : <<include>>
CallPatient --> ViewPatientInfo: <<include>>

CallPatient -> Patient: Call the patient

@enduml
