@startuml
actor CallCenterEmployee
actor Patient

rectangle MisterEdSystem {

    usecase ViewQueue
    usecase CallPatient
    usecase ViewPatientInfo
    usecase NotifyED

}

usecase ContactEmergencyServices


CallCenterEmployee -> ViewQueue : "Check current queue"
CallCenterEmployee -> ViewPatientInfo: "View patient information"
CallCenterEmployee -> CallPatient : "Proceed with next call"
CallCenterEmployee -> NotifyED : "Notify ED staff"

CallCenterEmployee -> ContactEmergencyServices : "Report emergency"


ViewPatientInfo --> ViewQueue : <<include>>
CallPatient --> ViewPatientInfo: <<include>>
NotifyED --> CallPatient : <<extend>>

CallPatient -> Patient: Call the patient

@enduml
