@startuml
actor CallCenterEmployee
actor Patient

rectangle MisterEdSystem {

    usecase ViewQueue
    usecase CallNextInQueue
    usecase ViewPatientInfo
    usecase NotifyED

}

usecase ContactEmergencyServices


CallCenterEmployee -> ViewQueue : "Check current queue"
CallCenterEmployee -> CallNextInQueue : "Proceed with next call"
CallCenterEmployee -> NotifyED : "Notify ED staff"

CallCenterEmployee -> ContactEmergencyServices : "Report emergency"

ViewQueue --> CallNextInQueue : <<include>>
CallNextInQueue --> ViewPatientInfo : <<include>>
NotifyED --> CallNextInQueue : <<extend>>

CallNextInQueue -> Patient: Call the patient

@enduml
