@startuml

left to right direction
actor "Medical Staff" as a

rectangle MisterEd as "Mister Ed" {
   usecase "Review Symptoms" as review_symptoms
   usecase "View Patient Medical History" as view_history
   usecase "Make Recommendation" as recommendation
   usecase "View Triage Queue" as view_queue
   review_symptoms .> view_history : extends
}

a --> review_symptoms
a --> view_queue
review_symptoms --> recommendation

@enduml
